M48
; DRILL file {KiCad (6.0.7)} date Wed Jun 14 22:42:16 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-14T22:42:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.4173Y-2.8622
X4.8307Y-6.0709
X6.9685Y-2.8622
X6.9685Y-6.0709
T2
X6.7826Y-3.2039
T3
X6.2826Y-3.2039
T1
G00X5.2058Y-5.8015
M15
G01X5.2058Y-5.8015
M16
G05
T0
M30
