M48
; DRILL file {KiCad (6.0.0)} date Sun Jul 24 20:25:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-24T20:25:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.6901Y-4.2883
T2
X6.1901Y-4.2883
T0
M30
