M48
; DRILL file {KiCad 7.0.5} date Wed Jun 28 23:37:26 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-28T23:37:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X5.3794Y-3.57
X5.3794Y-4.3574
X6.47Y-3.57
X6.47Y-4.3574
T2
X5.6901Y-4.2883
T3
X6.1901Y-4.2883
T0
M30
