M48
; DRILL file {KiCad (6.0.0)} date Sun Jul 24 20:20:58 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-24T20:20:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X6.0906Y-3.6132
X6.4831Y-3.6177
T2
X5.374Y-3.5236
X5.374Y-4.3504
X5.7386Y-4.283
X6.6142Y-4.3504
T3
X6.231Y-4.1962
T0
M30
