M48
; DRILL file {KiCad 7.0.1} date Sun Aug 13 11:11:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-13T11:11:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1260
%
G90
G05
T1
X5.8045Y-3.9744
X5.9955Y-3.9744
T2
X5.7927Y-3.8551
X6.0073Y-3.8551
T4
X4.95Y-3.85
T5
X4.45Y-3.85
T3
G00X5.0Y-5.79
M15
G01X5.0Y-5.79
M16
G05
T0
M30
