M48
; DRILL file {KiCad (6.0.7)} date Sat Feb 25 22:11:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-25T22:11:11-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.8Y-3.54
X5.8Y-3.65
X5.8487Y-3.8482
X5.91Y-3.49
X5.98Y-3.44
T2
X5.7Y-3.5
X5.7Y-3.6
X5.7Y-3.7
X5.7Y-3.8
X6.2Y-3.5
X6.2Y-3.6
X6.2Y-3.7
X6.2Y-3.8
T0
M30
