M48
; DRILL file {KiCad (6.0.6)} date Sat Jul  9 15:22:29 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-09T15:22:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X5.4Y-3.6
X6.65Y-3.6
T2
X5.55Y-4.1506
X5.925Y-3.0403
X6.6309Y-3.0417
T3
X5.425Y-3.0403
X6.05Y-4.1506
X6.1309Y-3.0417
T0
M30
